### PR TITLE
Source control release process

### LINKED ISSUE #111: Moving release process code to git repo
Currently the release tool is configured as freestyle job using shell script to build. https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/. It will be nice to upgrade to pipeline job so the job configuration can also be moved to git repo.

### PR DESCRIPTION
**Pull request by sophia-guo**
Move release job setting and code to git repo
Only upload test results for releases

Fix #111 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Need to double check the correct of way to set password parameter GITHUB_TOKEN

**Comment by sophia-guo** [comment]
Note, when update the job configuration parameter UPLOAD_TAPS_ONLY need to explicate removed, which is renamed to UPLOAD_TESTRESULTS_ONLY

**Review by karianna — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Note: Path to releaseCheck.sh in here was incorrect, fixed in https://github.com/adoptium/github-release-scripts/pull/122

**Comment by gdams** [comment]
@sophia-guo did this ever get put into production? Looking at the refactor release job it still seems to be manually defined?

**Comment by sophia-guo** [comment]
I setup a new job and tested, should be good to go though has not be put into production https://ci.adoptium.net/view/all/job/refactor_openjdk_release_tool_new/.

**Pull request merged**
